# This is a basic workflow to help you get started with Actions

name: Django CD

# Controls when the action will run. 
on:
  push:
    branches: 
        - backend

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    #if: github.ref == 'refs/heads/frontend'
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Deploy using ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: 22
        script: |
          cd ~/github/TalkAboutAll/
          git checkout backend
          git pull origin backend
          git status
          pm2 stop django_with_pm2
          rm -r ~/github/tests/backend/
          cp -r ~/github/TalkAboutAll/web/backend/ ~/github/tests/
          cd ~/github/tests/backend/
          cp ~/github/tests/.env ~/github/tests/backend/talk_about_all/
          cp ~/github/tests/echosystem.config.json ~/github/tests/backend/talk_about_all/
          cp -r ~/github/tests/data ~/github/tests/backend/talk_about_all/       
          pip install -r requirements.txt
          cd ~/github/tests/backend/talk_about_all/
          python3 manage.py makemigrations
          python3 manage.py migrate
          python3 manage.py load_csv
          pm2 start echosystem.config.json
